#include "crashHandler.h" //! generated by AI n edited by Vini
#include "../Includes.h"
#include <Windows.h>
#include <Psapi.h>
#include <ctime>
#include <sstream>
#include <iomanip>
#pragma comment(lib, "Psapi.lib")

using namespace PhasmoCheatV;

namespace
{
    PVOID g_VectoredHandle = nullptr;
    volatile LONG g_Handling = 0;

    const char* ExceptionCodeToString(DWORD code)
    {
        switch (code)
        {
        case EXCEPTION_ACCESS_VIOLATION:         return "EXCEPTION_ACCESS_VIOLATION";
        case EXCEPTION_STACK_OVERFLOW:           return "EXCEPTION_STACK_OVERFLOW";
        case EXCEPTION_ILLEGAL_INSTRUCTION:      return "EXCEPTION_ILLEGAL_INSTRUCTION";
        case EXCEPTION_PRIV_INSTRUCTION:         return "EXCEPTION_PRIV_INSTRUCTION";
        case EXCEPTION_IN_PAGE_ERROR:            return "EXCEPTION_IN_PAGE_ERROR";
        case EXCEPTION_INT_DIVIDE_BY_ZERO:       return "EXCEPTION_INT_DIVIDE_BY_ZERO";
        case EXCEPTION_NONCONTINUABLE_EXCEPTION: return "EXCEPTION_NONCONTINUABLE_EXCEPTION";
        case EXCEPTION_ARRAY_BOUNDS_EXCEEDED:    return "EXCEPTION_ARRAY_BOUNDS_EXCEEDED";
        case EXCEPTION_FLT_DIVIDE_BY_ZERO:       return "EXCEPTION_FLT_DIVIDE_BY_ZERO";
        case EXCEPTION_DATATYPE_MISALIGNMENT:    return "EXCEPTION_DATATYPE_MISALIGNMENT";
        default:                                 return "UNKNOWN_EXCEPTION";
        }
    }

    bool IsFatalException(DWORD code)
    {
        switch (code)
        {
        case EXCEPTION_ACCESS_VIOLATION:
        case EXCEPTION_STACK_OVERFLOW:
        case EXCEPTION_ILLEGAL_INSTRUCTION:
        case EXCEPTION_PRIV_INSTRUCTION:
        case EXCEPTION_IN_PAGE_ERROR:
        case EXCEPTION_INT_DIVIDE_BY_ZERO:
        case EXCEPTION_NONCONTINUABLE_EXCEPTION:
        case EXCEPTION_ARRAY_BOUNDS_EXCEEDED:
            return true;

        default:
            return false;
        }
    }

    std::string GetDateTime()
    {
        std::time_t now = std::time(nullptr);
        std::tm localTime{};

        localtime_s(&localTime, &now);

        std::ostringstream stream;

        stream << std::setfill('0')
            << std::setw(2) << localTime.tm_mon + 1
            << "."
            << std::setw(2) << localTime.tm_mday
            << "."
            << std::setw(4) << localTime.tm_year + 1900
            << " "
            << std::setw(2) << localTime.tm_hour
            << ":"
            << std::setw(2) << localTime.tm_min
            << ":"
            << std::setw(2) << localTime.tm_sec;

        return stream.str();
    }

    LONG WINAPI VectoredCrashHandler(EXCEPTION_POINTERS* info);
    HMODULE GetCurrentModule()
    {
        HMODULE module = nullptr;

        GetModuleHandleExA(
            GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            reinterpret_cast<LPCSTR>(&VectoredCrashHandler),
            &module);

        return module;
    }

    uintptr_t GetModuleBase(const char* moduleName)
    {
        HMODULE module = GetModuleHandleA(moduleName);
        return reinterpret_cast<uintptr_t>(module);
    }

    uintptr_t GetModuleFromAddress(const void* address)
    {
        if (!address)
            return 0;

        HMODULE module = nullptr;

        if (!GetModuleHandleExA(
            GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            reinterpret_cast<LPCSTR>(address),
            &module))
        {
            return 0;
        }

        return reinterpret_cast<uintptr_t>(module);
    }

    std::string GetModuleNameFromAddress(const void* address)
    {
        if (!address)
            return "UNKNOWN";

        HMODULE module = nullptr;

        if (!GetModuleHandleExA(
            GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            reinterpret_cast<LPCSTR>(address),
            &module))
        {
            return "UNKNOWN";
        }

        char path[MAX_PATH]{};

        if (!GetModuleFileNameA(module, path, MAX_PATH))
            return "UNKNOWN";

        const char* name = strrchr(path, '\\');

        return name ? name + 1 : path;
    }

    std::string GetModuleVersion(HMODULE module)
    {
        if (!module)
            return "UNKNOWN";

        char path[MAX_PATH]{};

        if (!GetModuleFileNameA(module, path, MAX_PATH))
            return "UNKNOWN";

        DWORD handle = 0;

        const DWORD size = GetFileVersionInfoSizeA(path, &handle);

        if (!size)
            return "UNKNOWN";

        std::vector<BYTE> data(size);

        if (!GetFileVersionInfoA(path, 0, size, data.data()))
            return "UNKNOWN";

        VS_FIXEDFILEINFO* fileInfo = nullptr;
        UINT fileInfoSize = 0;

        if (!VerQueryValueA(
            data.data(),
            "\\",
            reinterpret_cast<LPVOID*>(&fileInfo),
            &fileInfoSize))
        {
            return "UNKNOWN";
        }

        if (!fileInfo)
            return "UNKNOWN";

        std::ostringstream stream;

        stream
            << HIWORD(fileInfo->dwFileVersionMS) << "."
            << LOWORD(fileInfo->dwFileVersionMS) << "."
            << HIWORD(fileInfo->dwFileVersionLS) << "."
            << LOWORD(fileInfo->dwFileVersionLS);

        return stream.str();
    }

    void WriteCrashToFile(const char* text)
    {
        try
        {
            std::string dir = Utils::GetPhasmoCheatVDirectory();

            if (dir.empty())
                dir = "C:\\VComDev\\PhasmoCheatV";

            std::string crashDir = dir + "\\crashes";

            CreateDirectoryA(crashDir.c_str(), nullptr);

            const std::string dateTime = GetDateTime();

            std::time_t now = std::time(nullptr);
            std::tm localTime{};

            localtime_s(&localTime, &now);

            char fileName[128]{};

            sprintf_s(
                fileName,
                "%02d.%02d.%04d_%02d-%02d-%02d.txt",
                localTime.tm_mon + 1,
                localTime.tm_mday,
                localTime.tm_year + 1900,
                localTime.tm_hour,
                localTime.tm_min,
                localTime.tm_sec);

            std::string path = crashDir + "\\" + fileName;

            HANDLE hFile = CreateFileA(
                path.c_str(),
                FILE_APPEND_DATA,
                FILE_SHARE_READ | FILE_SHARE_WRITE,
                nullptr,
                OPEN_ALWAYS,
                FILE_ATTRIBUTE_NORMAL,
                nullptr);

            if (hFile == INVALID_HANDLE_VALUE)
                return;

            DWORD written = 0;

            WriteFile(
                hFile,
                text,
                static_cast<DWORD>(strlen(text)),
                &written,
                nullptr);

            FlushFileBuffers(hFile);
            CloseHandle(hFile);
        }
        catch (...)
        {
            // time moves too fast...
        }
    }

    LONG WINAPI VectoredCrashHandler(EXCEPTION_POINTERS* info)
    {
        if (InterlockedCompareExchange(&g_Handling, 1, 0) != 0)
            return EXCEPTION_CONTINUE_SEARCH;

        if (!info || !info->ExceptionRecord)
        {
            InterlockedExchange(&g_Handling, 0);
            return EXCEPTION_CONTINUE_SEARCH;
        }

        const DWORD code = info->ExceptionRecord->ExceptionCode;

        if (!IsFatalException(code))
        {
            InterlockedExchange(&g_Handling, 0);
            return EXCEPTION_CONTINUE_SEARCH;
        }

        const auto* record = info->ExceptionRecord;
        const auto* context = info->ContextRecord;

        const uintptr_t exceptionAddress =
            reinterpret_cast<uintptr_t>(record->ExceptionAddress);

        const uintptr_t gameAssemblyBase =
            GetModuleBase("GameAssembly.dll");

        const HMODULE ownModule =
            GetCurrentModule();

        const uintptr_t ownModuleBase =
            reinterpret_cast<uintptr_t>(ownModule);

        const uintptr_t exceptionModuleBase =
            GetModuleFromAddress(record->ExceptionAddress);

        const std::string exceptionModuleName =
            GetModuleNameFromAddress(record->ExceptionAddress);

        const std::string ownModuleName =
            ownModule
            ? GetModuleNameFromAddress(reinterpret_cast<void*>(ownModuleBase))
            : "UNKNOWN";

        std::ostringstream log;

        log << "DATE: " << GetDateTime() << "\n";

        log << "PROCESS:\n";
        log << "  PID: " << GetCurrentProcessId() << "\n";
        log << "  TID: " << GetCurrentThreadId() << "\n";
        log << "  EXE Base: " << reinterpret_cast<void*>(GetModuleBase(nullptr)) << "\n";

        log << "\nGAME:\n";
        log << "  Game Version: " << Utils::GetGameVersion() << "\n";
        log << "  GameAssembly.dll Base: "
            << reinterpret_cast<void*>(gameAssemblyBase) << "\n";

        log << "\nCHEAT DLL:\n";
        log << "  Module: " << ownModuleName << "\n";
        log << "  Base: "
            << reinterpret_cast<void*>(ownModuleBase) << "\n";
        log << "  Version: "
            << GetModuleVersion(ownModule) << "\n";

        log << "\nEXCEPTION:\n";
        log << "  Code: 0x"
            << std::uppercase
            << std::hex
            << std::setw(8)
            << std::setfill('0')
            << code
            << std::dec
            << "\n";

        log << "  Type: " << ExceptionCodeToString(code) << "\n";

        log << "  Address: "
            << reinterpret_cast<void*>(exceptionAddress)
            << "\n";

        log << "  Module: "
            << exceptionModuleName
            << "\n";

        log << "  Module Base: "
            << reinterpret_cast<void*>(exceptionModuleBase)
            << "\n";

        if (exceptionModuleBase && exceptionAddress >= exceptionModuleBase)
        {
            log << "  Module Offset: 0x"
                << std::uppercase
                << std::hex
                << (exceptionAddress - exceptionModuleBase)
                << std::dec
                << "\n";
        }

        if (code == EXCEPTION_ACCESS_VIOLATION &&
            record->NumberParameters >= 2)
        {
            const ULONG_PTR accessType =
                record->ExceptionInformation[0];

            const ULONG_PTR accessAddress =
                record->ExceptionInformation[1];

            const char* accessString =
                accessType == 0
                ? "READ"
                : accessType == 1
                ? "WRITE"
                : "EXECUTE";

            log << "\nACCESS VIOLATION:\n";
            log << "  Type: " << accessString << "\n";
            log << "  Address: "
                << reinterpret_cast<void*>(accessAddress)
                << "\n";
        }

        if (code == EXCEPTION_IN_PAGE_ERROR &&
            record->NumberParameters >= 3)
        {
            log << "\nIN PAGE ERROR:\n";
            log << "  Operation: "
                << record->ExceptionInformation[0]
                << "\n";

            log << "  Address: "
                << reinterpret_cast<void*>(
                    record->ExceptionInformation[1])
                << "\n";

            log << "  NTSTATUS: 0x"
                << std::uppercase
                << std::hex
                << record->ExceptionInformation[2]
                << std::dec
                << "\n";
        }

#ifdef _M_X64
        if (context)
        {
            log << "\nREGISTERS:\n";

            log << "  RIP: "
                << reinterpret_cast<void*>(context->Rip)
                << "\n";

            log << "  RSP: "
                << reinterpret_cast<void*>(context->Rsp)
                << "\n";

            log << "  RBP: "
                << reinterpret_cast<void*>(context->Rbp)
                << "\n";

            log << "  RAX: "
                << reinterpret_cast<void*>(context->Rax)
                << "\n";

            log << "  RBX: "
                << reinterpret_cast<void*>(context->Rbx)
                << "\n";

            log << "  RCX: "
                << reinterpret_cast<void*>(context->Rcx)
                << "\n";

            log << "  RDX: "
                << reinterpret_cast<void*>(context->Rdx)
                << "\n";

            log << "  RSI: "
                << reinterpret_cast<void*>(context->Rsi)
                << "\n";

            log << "  RDI: "
                << reinterpret_cast<void*>(context->Rdi)
                << "\n";

            log << "  R8:  "
                << reinterpret_cast<void*>(context->R8)
                << "\n";

            log << "  R9:  "
                << reinterpret_cast<void*>(context->R9)
                << "\n";

            log << "  R10: "
                << reinterpret_cast<void*>(context->R10)
                << "\n";

            log << "  R11: "
                << reinterpret_cast<void*>(context->R11)
                << "\n";

            log << "  R12: "
                << reinterpret_cast<void*>(context->R12)
                << "\n";

            log << "  R13: "
                << reinterpret_cast<void*>(context->R13)
                << "\n";

            log << "  R14: "
                << reinterpret_cast<void*>(context->R14)
                << "\n";

            log << "  R15: "
                << reinterpret_cast<void*>(context->R15)
                << "\n";

            log << "  EFlags: 0x"
                << std::uppercase
                << std::hex
                << context->EFlags
                << std::dec
                << "\n";
        }
#endif

        log << "\nEXCEPTION PARAMETERS:\n";

        for (DWORD i = 0; i < record->NumberParameters; ++i)
        {
            log << "  [" << i << "] 0x"
                << std::uppercase
                << std::hex
                << record->ExceptionInformation[i]
                << std::dec
                << "\n";
        }

        const std::string logString = log.str();

        if (logger)
            LOG_ERROR("CRASH!!! ", logString.c_str());

        WriteCrashToFile(logString.c_str());

        InterlockedExchange(&g_Handling, 0);

        return EXCEPTION_CONTINUE_SEARCH;
    }
}

namespace PhasmoCheatV::CrashHandler
{
    bool Install()
    {
        if (g_VectoredHandle)
            return true;

        g_VectoredHandle =
            AddVectoredExceptionHandler(
                1,
                VectoredCrashHandler);

        if (g_VectoredHandle)
        {
            LOG_INFO("VEH installed (crashHandler)");
            return true;
        }

        LOG_ERROR("Failed to install CrashHandler");
        return false;
    }

    void Uninstall()
    {
        if (g_VectoredHandle)
        {
            RemoveVectoredExceptionHandler(g_VectoredHandle);
            g_VectoredHandle = nullptr;

            LOG_INFO("CrashHandler uninstalled");
        }
    }

    bool IsInstalled()
    {
        return g_VectoredHandle != nullptr;
    }
}